easy_admin:
    site_name: Astronomie Conference
    design:
        menu:
            - { entity: 'Conference', label: 'Conferences', icon: 'map-marker' }
            - { entity: 'Commentaire', label: 'Commentaires', icon: 'comments' }
            - { entity: 'Livre', label: 'Livres', icon: 'book' }
            - { entity: 'Commande', label: 'Commandes', icon: 'shopping-cart'}
    entities:
        # List the entity class name you want to manage
        Conference:
            class: App\Entity\Conference

        Commentaire:
            class: App\Entity\Commentaire

        Livre:
            class: App\Entity\Livre

        Commande:
            class: App\Entity\Commande


      #  - App\Entity\Commentaire
      #  - App\Entity\Livre
      #  - App\Entity\Commande
